chore: fix minor build issues (#25)
* Ignore invalid path selector BoardConfig*.mk (better to ignore than to remove)

[daniel@xps15 jetkvm-system]$ ./build.sh lunch BoardConfig_IPC/BoardConfig-EMMC-NONE-RV1106_JETKVM_V2.mk
ls: cannot access 'BoardConfig*.mk': No such file or directory
BoardConfig_IPC/BoardConfig-EMMC-NONE-RV1106_JETKVM_V2.mk
[build.sh:info] switching to board: /home/daniel/Projects/jetkvm-system/project/cfg/BoardConfig_IPC/BoardConfig-EMMC-NONE-RV1106_JETKVM_V2.mk
[build.sh:info] Running build_select_board succeeded.

* Ignore RK-RELEASE-NOTES-IPC.txt

* Fix util/subst.c not compiling. HAVE_CONFIG_H is *not* set, resulting in below
error message. More recent version of util/subst.c also define HAVE_SYS_STAT_H.
This adds an in-line patch. Alternatively, a more recent version of e2fsprogs
could be used.

subst.c: In function 'main':
subst.c:391:29: error: implicit declaration of function 'fstat' [-Wimplicit-function-declaration]
  391 |                         if (fstat(fd, &stbuf) == 0) {
      |                             ^~~~~
subst.c:437:40: error: implicit declaration of function 'fchmod' [-Wimplicit-function-declaration]
  437 |                                 (void) fchmod(ofd, 0444);
      |                                        ^~~~~~
make[3]: *** [Makefile:329: subst.o] Error 1
make[2]: *** [Makefile:177: util/subst] Error 2
make[1]: *** [Makefile:16: all] Error 255
make[1]: Leaving directory '/home/daniel/Projects/jetkvm-system/sysdrv/tools/board/e2fsprogs'
make: *** [/home/daniel/Projects/jetkvm-system/sysdrv/tools/board/Makefile.tools.board.mk:73: board-build-e2fsprogs] Error 2
make: Leaving directory '/home/daniel/Projects/jetkvm-system/sysdrv'
[build.sh:error] Running build_rootfs failed!
[build.sh:error] exit code 2 from line 655:
[build.sh:info]     make rootfs -C ${SDK_SYSDRV_DIR}